import type { Achievement, PlantStats } from '../types'

export interface PlantAchievementDef extends Achievement {
  condition: (stats: PlantStats) => boolean
}

export const PLANT_ACHIEVEMENTS: PlantAchievementDef[] = [
  // ─── КОЛЛЕКЦИЯ ────────────────────────────────────────────────────────────
  {
    id: 'plant_first',
    name: 'Первый росток',
    description: 'Определи своё первое растение',
    icon: '🌱',
    category: 'collection',
    points: 10,
    rarity: 'bronze',
    condition: (s) => s.uniqueSpecies >= 1,
  },
  {
    id: 'plant_5',
    name: 'Начинающий ботаник',
    description: 'Найди 5 разных видов растений',
    icon: '🌿',
    category: 'collection',
    points: 25,
    rarity: 'bronze',
    condition: (s) => s.uniqueSpecies >= 5,
  },
  {
    id: 'plant_10',
    name: 'Любитель флоры',
    description: 'Найди 10 разных видов растений',
    icon: '🍀',
    category: 'collection',
    points: 50,
    rarity: 'bronze',
    condition: (s) => s.uniqueSpecies >= 10,
  },
  {
    id: 'plant_25',
    name: 'Знаток растений',
    description: 'Найди 25 разных видов растений',
    icon: '🌳',
    category: 'collection',
    points: 100,
    rarity: 'silver',
    condition: (s) => s.uniqueSpecies >= 25,
  },
  {
    id: 'plant_50',
    name: 'Опытный ботаник',
    description: 'Найди 50 разных видов растений',
    icon: '🏵️',
    category: 'collection',
    points: 200,
    rarity: 'gold',
    condition: (s) => s.uniqueSpecies >= 50,
  },
  {
    id: 'plant_100',
    name: 'Мастер флористики',
    description: 'Найди 100 разных видов растений',
    icon: '🌺',
    category: 'collection',
    points: 500,
    rarity: 'platinum',
    condition: (s) => s.uniqueSpecies >= 100,
  },
  {
    id: 'plant_total_10',
    name: 'Юный ботаник',
    description: 'Сделай 10 наблюдений за растениями',
    icon: '📋',
    category: 'collection',
    points: 20,
    rarity: 'bronze',
    condition: (s) => s.totalPlants >= 10,
  },
  {
    id: 'plant_total_50',
    name: 'Усердный ботаник',
    description: 'Сделай 50 наблюдений за растениями',
    icon: '📊',
    category: 'collection',
    points: 75,
    rarity: 'silver',
    condition: (s) => s.totalPlants >= 50,
  },

  // ─── ТАКСОНОМИЯ ───────────────────────────────────────────────────────────
  {
    id: 'plant_families_3',
    name: 'Разнообразие',
    description: 'Найди растения из 3 разных семейств',
    icon: '🌸',
    category: 'taxonomy',
    points: 40,
    rarity: 'bronze',
    condition: (s) => s.families.length >= 3,
  },
  {
    id: 'plant_families_7',
    name: 'Систематик-ботаник',
    description: 'Найди растения из 7 разных семейств',
    icon: '🌼',
    category: 'taxonomy',
    points: 120,
    rarity: 'silver',
    condition: (s) => s.families.length >= 7,
  },
  {
    id: 'plant_families_15',
    name: 'Энциклопедист флоры',
    description: 'Найди растения из 15 разных семейств',
    icon: '🔬',
    category: 'taxonomy',
    points: 300,
    rarity: 'gold',
    condition: (s) => s.families.length >= 15,
  },
  {
    id: 'plant_fungus',
    name: 'Первый гриб',
    description: 'Найди и определи гриб',
    icon: '🍄',
    category: 'taxonomy',
    points: 30,
    rarity: 'bronze',
    condition: (s) => s.fungi >= 1,
  },
  {
    id: 'plant_fungi_5',
    name: 'Грибник',
    description: 'Найди 5 разных грибов',
    icon: '🍄',
    category: 'taxonomy',
    points: 80,
    rarity: 'silver',
    condition: (s) => s.fungi >= 5,
  },
  {
    id: 'plant_big_day',
    name: 'Зелёный день',
    description: 'Найди 5 видов растений за один день',
    icon: '⚡',
    category: 'taxonomy',
    points: 100,
    rarity: 'silver',
    condition: (s) => {
      const byDay: Record<string, Set<string>> = {}
      for (const obs of s.observations) {
        const day = obs.observedAt.slice(0, 10)
        if (!byDay[day]) byDay[day] = new Set()
        byDay[day].add(obs.plant.id)
      }
      return Object.values(byDay).some((set) => set.size >= 5)
    },
  },

  // ─── ВРЕМЯ ────────────────────────────────────────────────────────────────
  {
    id: 'plant_morning',
    name: 'Утренняя прогулка',
    description: 'Определи растение до 7 утра',
    icon: '🌅',
    category: 'time',
    points: 25,
    rarity: 'bronze',
    condition: (s) => s.earlyMorning >= 1,
  },
  {
    id: 'plant_night',
    name: 'Ночной ботаник',
    description: 'Определи растение после 23:00',
    icon: '🌙',
    category: 'time',
    points: 40,
    rarity: 'silver',
    condition: (s) => s.lateNight >= 1,
  },
  {
    id: 'plant_streak_3',
    name: 'Три дня с природой',
    description: 'Наблюдай за растениями 3 дня подряд',
    icon: '🔥',
    category: 'time',
    points: 40,
    rarity: 'bronze',
    condition: (s) => s.streak >= 3,
  },
  {
    id: 'plant_streak_7',
    name: 'Неделя с природой',
    description: 'Наблюдай за растениями 7 дней подряд',
    icon: '📅',
    category: 'time',
    points: 150,
    rarity: 'gold',
    condition: (s) => s.streak >= 7,
  },

  // ─── ИССЛЕДОВАНИЯ ─────────────────────────────────────────────────────────
  {
    id: 'plant_explorer',
    name: 'Флора в трёх местах',
    description: 'Найди растения в 3 разных местах',
    icon: '🗺️',
    category: 'exploration',
    points: 80,
    rarity: 'silver',
    condition: (s) => s.locations.length >= 3,
  },
  {
    id: 'plant_traveler',
    name: 'Флора в пяти местах',
    description: 'Найди растения в 5 разных местах',
    icon: '🧭',
    category: 'exploration',
    points: 150,
    rarity: 'gold',
    condition: (s) => s.locations.length >= 5,
  },
  {
    id: 'plant_explorer_10',
    name: 'Первооткрыватель флоры',
    description: 'Найди растения в 10 разных местах',
    icon: '🌍',
    category: 'exploration',
    points: 350,
    rarity: 'platinum',
    condition: (s) => s.locations.length >= 10,
  },
]
